---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sre-operator-reinstall-sa
  namespace: openshift-managed-upgrade-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sre-operator-reinstall-role
  namespace: openshift-managed-upgrade-operator
rules:
  - apiGroups:
      - "operators.coreos.com"
    resources:
      - clusterserviceversions
      - subscriptions
      - installplans
    verbs:
      - list
      - get
      - delete
      - create
  - apiGroups:
      - "batch"
    resources:
      - cronjobs
    verbs:
      - list
      - get
      - delete
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - list
      - get
      - delete
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - roles
      - rolebindings
    verbs:
      - list
      - get
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sre-operator-reinstall-rb
  namespace: openshift-managed-upgrade-operator
roleRef:
  kind: Role
  name: sre-operator-reinstall-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: sre-operator-reinstall-sa
    namespace: openshift-managed-upgrade-operator
